# 本地环境下专用的配置文件
[log] # 日志相关配置
filedir = "./logs/" #日志文件路径
level = 5 #日志保存的时候的级别，默认是 Info 级别

[db]
dzsns = "root:root@(mysql:3306)/bbs_local?parseTime=true&loc=Local&charset=utf8"
write_log = true # 数据库操作是否写日志。


[redis]
server = "redis:6379"
password = "12345678"

[login]
check_url = "http://localhost:8889/m/index.php?s=/capi/check_login.html"