# 本地环境下专用的配置文件
[log] # 日志相关配置
level = 5 #日志保存的时候的级别，默认是 Info 级别

[db]
server = "root:root@(mysql:3306)/bbs_local?parseTime=true&loc=Local&charset=utf8"
write_log = true # 数据库操作是否写日志。


[redis]
server = "redis:6379"
password = "12345678"

[login]
check_url = ""

[pprof]
server= ":40041"